# Generated by Django 4.0.4 on 2022-05-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frischboxadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='status',
        ),
        migrations.AddField(
            model_name='packages',
            name='Delivery_Days',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='Delivery_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='paylink',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
